[package]
name = "poseidon2_circuit"
type = "bin"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
poseidon2 = { tag = "v0.4.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2" } 